### ISSUE TITLE
no Port Exposed

### ISSUE THREAD

**Issue by nileio** [Chorss/docker-pgAdmin4#18]
Hi ,
I am not sure if i am missing something
 i cant see an EXPOSE line.
So there is no exposed port ? I see previous builds have EXPOSE 
usually port 5050

Thanks

**Comment by Chorss** [comment]
Hi,
I removed this instruction because I considered unnecessary. I understand that it has to restore it?

> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published.

**Comment by nileio** [comment]
this is good to know.. however, bear in mind that leaving the EXPOSE instruction enables some automated apps to run the container correctly ! example Portainer.. If you take it out, then there is no way for an automated approach to run your container.. I dont think it saves anything by removing it too from a usability perspective, and it is more readable and self-explanatory rather than relying on the documentation. I suggest to have it back ?

**Comment by Chorss** [comment]
Understand so I restored the command.
Thank you very much
